index:
    path: /
    controller: 'App\Controller\DefaultController::index'

chests:
    path: items/truhen
    controller: 'App\Controller\ChestsController::index'

collectionitems:
    path: items/sammelitems/{character}
    controller: 'App\Controller\CollectionItemsController::index'
    defaults:
        character: null
