index:
    path: /
    controller: 'App\Controller\DefaultController::index'

missions:
    path: /missionen/{chapter}
    controller: 'App\Controller\MissionsController::index'
    defaults:
        chapter: null

chests:
    path: items/truhen
    controller: 'App\Controller\ChestsController::index'

collectionitems:
    path: items/sammelitems/{character}
    controller: 'App\Controller\CollectionItemsController::index'
    defaults:
        character: null

storyfights:
    path: guides/handlungskampfe
    controller: 'App\Controller\StoryFightsController::index'
